language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="6.7"
    - RACKET_VERSION="6.8"
    - RACKET_VERSION="HEAD"
    - RACKET_VERSION="RELEASE"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"
    - env: RACKET_VERSION="RELEASE"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
 - raco pkg install --auto -n video

script:
 - raco test --package video
 - raco setup